language: c
compiler: gcc
sudo: required
dist: xenial
cache:
  - apt
before_install:
  - sudo add-apt-repository ppa:vala-team -y
  - sudo apt -qq update
  - sudo apt install -y cmake valac libgtk-3-dev libappindicator3-dev gettext kdeconnect python3-requests-oauthlib
before_script:
  - sleep 3
script:
  - mkdir build
  - cd build  
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
  - make
