language: c
compiler: gcc
sudo: required
dist: xenial
cache:
  - apt
before_install:
  - sudo add-apt-repository ppa:vala-team -y
  - sudo apt -qq update
  - sudo apt install -y ninja meson valac libgtk-3-dev libappindicator3-dev libgee-0.8-dev gettext  kdeconnect python3-requests-oauthlib
before_script:
  - sleep 3
script:
  - mkdir build
  - cd build  
  - meson .. --prefix=/usr/  --libdir=/usr/lib/
  - meson configure -Dconfig_folder=$HOME/.local/share/ -Dextensions=python
  - ninja
